### ISSUE TITLE
Add documentation?

### ISSUE THREAD

**Issue by stapelberg** [u-root/cpu#4]
It’s not entirely clear how to use this tool: what are the requirements in terms of permissions and environment on the local and remote machine? Could a few example invocations be described?

Thanks,

**Comment by hugelgupf** [comment]
I would suggest starting with moving the godoc to the readme. https://github.com/u-root/cpu/blob/master/cmds/cpu/doc.go @rminnich

**Comment by mpictor** [comment]
The files [cpu/doc.go](https://github.com/u-root/cpu/blob/master/cmds/cpu/doc.go) and [cpud/doc.go](https://github.com/u-root/cpu/blob/master/cmds/cpud/doc.go) are identical. Is this intentional?

Rather than duplicating the documentation from godoc, what about specifically mentioning godoc in the README?

Also, the URL for the `godoc` icon in the README should be updated to point to u-root/cpu - currently it points to godoc for u-root/u-root.

**Comment by mpictor** [comment]
I'd also like to see documentation of how to create the keys, and whether any specific kernel options must be enabled/disabled; so far I've manged to get `cpu` to spit out the key I pass to it, complaining of a short read, or to tell me `connection reset by peer`.

**Comment by orangecms** [comment]
Coming back to this:
I had drafted initial notes in https://github.com/orangecms/arm-cpu#executing-over-cpu
I'll see that I can find some time again to expand that and get it in here.

**Comment by orangecms** [comment]
We've configured https://book.linuxboot.org/ for a start and Ron added a few links to the cpu chapter in it and talks featuring cpu to the README; WDYT @stapelberg, is that a good start?

**Comment by stapelberg** [comment]
Thanks, https://book.linuxboot.org/cpu/ is a good read and indeed answers my questions! :)

**Comment by orangecms** [comment]
Awesome, thank you! We've extended the README even more and added the link to the cpu chapter in the book. Closing then, enjoy `cpu`! :)
